version: '3.8'

services:
  ui:
    build: ./ui
    ports:
      - "5000:5000"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
